"""Initial migration

Revision ID: 99c92bf79594
Revises: 
Create Date: 2026-03-14 09:44:24.779049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99c92bf79594'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 将原来 downgrade() 的内容复制到这里
    op.create_table('news_category',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='分类ID'),
                    sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='分类名称'),
                    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='排序顺序'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='新闻分类表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='新闻分类表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('name_UNIQUE'), 'news_category', ['name'], unique=True)
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='用户ID'),
                    sa.Column('username', mysql.VARCHAR(length=50), nullable=False, comment='用户名'),
                    sa.Column('password', mysql.VARCHAR(length=255), nullable=False, comment='密码（加密存储）'),
                    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=True, comment='昵称'),
                    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True, comment='头像URL'),
                    sa.Column('gender', mysql.ENUM('male', 'female', 'unknown'), server_default=sa.text("'unknown'"), nullable=True, comment='性别'),
                    sa.Column('bio', mysql.VARCHAR(length=500), nullable=True, comment='个人简介'),
                    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True, comment='手机号'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='用户信息表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='用户信息表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('username_UNIQUE'), 'user', ['username'], unique=True)
    op.create_index(op.f('phone_UNIQUE'), 'user', ['phone'], unique=True)
    op.create_table('ai_chat',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='聊天记录ID'),
                    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
                    sa.Column('message', mysql.TEXT(), nullable=False, comment='用户消息'),
                    sa.Column('response', mysql.TEXT(), nullable=False, comment='AI回复'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ai_chat_user'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='AI聊天记录表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='AI聊天记录表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('idx_created_at'), 'ai_chat', ['created_at'], unique=False)
    op.create_index(op.f('fk_ai_chat_user_idx'), 'ai_chat', ['user_id'], unique=False)
    op.create_table('news',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='新闻ID'),
                    sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='新闻标题'),
                    sa.Column('description', mysql.VARCHAR(length=500), nullable=True, comment='新闻简介'),
                    sa.Column('content', mysql.TEXT(), nullable=False, comment='新闻内容'),
                    sa.Column('image', mysql.VARCHAR(length=255), nullable=True, comment='封面图片URL'),
                    sa.Column('author', mysql.VARCHAR(length=50), nullable=True, comment='作者'),
                    sa.Column('category_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='分类ID'),
                    sa.Column('views', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='浏览量'),
                    sa.Column('publish_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='发布时间'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
                    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], name=op.f('fk_news_category'), onupdate='CASCADE', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='新闻表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='新闻表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('idx_publish_time'), 'news', ['publish_time'], unique=False)
    op.create_index(op.f('fk_news_category_idx'), 'news', ['category_id'], unique=False)
    op.create_table('user_token',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='令牌ID'),
                    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
                    sa.Column('token', mysql.VARCHAR(length=255), nullable=False, comment='令牌值'),
                    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=False, comment='过期时间'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_token_user'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='用户令牌表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='用户令牌表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('token_UNIQUE'), 'user_token', ['token'], unique=True)
    op.create_index(op.f('fk_user_token_user_idx'), 'user_token', ['user_id'], unique=False)
    op.create_table('favorite',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='收藏ID'),
                    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
                    sa.Column('news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='新闻ID'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='收藏时间'),
                    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_favorite_news'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_user'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='收藏表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='收藏表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('user_news_unique'), 'favorite', ['user_id', 'news_id'], unique=True)
    op.create_index(op.f('fk_favorite_user_idx'), 'favorite', ['user_id'], unique=False)
    op.create_index(op.f('fk_favorite_news_idx'), 'favorite', ['news_id'], unique=False)
    op.create_table('history',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='历史ID'),
                    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
                    sa.Column('news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='新闻ID'),
                    sa.Column('view_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='浏览时间'),
                    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_history_news'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_history_user'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='浏览历史表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='浏览历史表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('idx_view_time'), 'history', ['view_time'], unique=False)
    op.create_index(op.f('fk_history_user_idx'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('fk_history_news_idx'), 'history', ['news_id'], unique=False)
    op.create_table('related_news',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='关联ID'),
                    sa.Column('news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='新闻ID'),
                    sa.Column('related_news_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='相关新闻ID'),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
                    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_related_news_news'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['related_news_id'], ['news.id'], name=op.f('fk_related_news_related'), onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='相关新闻关联表',
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_comment='相关新闻关联表',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('news_related_unique'), 'related_news', ['news_id', 'related_news_id'], unique=True)
    op.create_index(op.f('fk_related_news_related_idx'), 'related_news', ['related_news_id'], unique=False)
    op.create_index(op.f('fk_related_news_news_idx'), 'related_news', ['news_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 将原来 upgrade() 的内容复制到这里，作为回滚操作
    op.drop_table('related_news')
    op.drop_table('history')
    op.drop_table('favorite')
    op.drop_table('user_token')
    op.drop_table('news')
    op.drop_table('ai_chat')
    op.drop_table('user')
    op.drop_table('news_category')
    # ### end Alembic commands ###

